name: 'Checkmarx CxFlow++ GitHub Action'
description: 'Orchestrates vulnerability scanning and issue tracker item lifecycle.'
author: 'Nathan Leach, Principal Solutions Architect, Checkmarx'

inputs:
  # Required parameters
  project-name:
    description: The name of the scan project.  This should include the branch being scanned using your organization's established system naming convention. The string `{branch}` will be replaced by the event's branch name if found in the project name.
  app-name:
    description: The name of the application used when making issue tracker tags.


  # Required unless disable-sast-scan is set to true
  sast-url:
    required: false
    description: The base URL to the Checkmarx SAST server (do not include CxWebClient).
  sast-team:
    required: false
    default: /CxServer
    description: The full path of the SAST team that owns the project to scan.
  sast-username:
    required: false
    description: The username of the SAST account to use for scanning.
  sast-password:
    required: false
    description: The password for the selected SAST account.

  # Required unless disable-sca-scan is set to true
  sca-tenant:
    required: false
    description: The name of the SCA tenant.
  sca-username:
    required: false
    description: The username of the SCA account to use for scanning.
  sca-password:
    required: false
    description: The password for the selected SCA account.

  # Optional parameters
  cxflow-jar-path:
    default: ''
    description: The local path to the CxFlow jar.  If blank, CxFlow will be downloaded.
  cxflow-version:
    default: latest
    description: The CxFlow version to use for execution.  Ignored if cxflow-jar-path is set.
  cxflow-params:
    description: Command line parameters to pass to CxFlow at every execution.
  pull-request-cxflow-params:
    description: Command line parameters passed to CxFlow only when executing during a pull-request event.
  push-cxflow-params:
    description: Command line parameters passed to CxFlow only when executing during a push event.

  docker-login-registry:
    default: docker.io
    description: The name of the container registry to use for login.
  docker-login-username:
    default: ''
    description: The username for the container registry login.
  docker-login-password:
    default: ''
    description: The password for the container registry login.

  upload-sarif-file:
    default: true
    description: Uploads the Sarif file to create entries on the GitHub security tab during push events. 
  delete-sarif-file:
    default: true
    description: Set to "false" when using the Sarif feedback channel to keep the Sarif file at the path returned in the sarif-path output parameter.


  default-branch:
    default: ${{ github.event.repository.default_branch }}
    description: The default branch of the repository used as the root parent project in SAST from which branch projects are derived.  This defaults to the repo's defined default branch.
  disable-sast-scan:
    default: false
    description: Set to true to disable SAST scanning.
  disable-sca-scan:
    default: false
    description: Set to true to disable SCA scanning.
  enable-wire-trace:
    default: false
    description: Set to true to emit web API I/O wire tracing to the action logs.
  sast-log-level:
    default: INFO
    description: The logging level for CxFlow output emitted as the action executes. (TRACE, DEBUG, ERROR, INFO)
  java-opts:
    default: -Xms512m -Xmx2048m
    description: Options to pass to the JVM.
  java-props:
    default: -Djava.security.egd=file:/dev/./urandom
    description: Properties to pass to the JVM.
  push-feedback-channel:
    default: Sarif
    description: The feedback channel to use when scanning for a push.
  pull-request-feedback-channel:
    default: GITHUBPULL
    description: The feedback channel to use when scanning for a pull request.
  application-yaml-path:
    default: ''
    description: A path to a CxFlow yaml configuration file.
  build-container-tag:
    default: ''
    description: Set the the tag of the container used to perform the code build.  SCA Resolver will execute in an instance of this container to obtain an accurate dependency tree.
  scaresolver-tag:
    default: ''
    description: The tag for the containerized SCAResolver build environment where the action will execute dependency scanning.  The image must not be built with a *-bare target. If this is not supplied, the SCA dependency scan will execute on the SCA server.
  spring-props:
    default: ''
    description: Spring boot properties to pass to the JVM.
  custom-ca-path:
    default: ''
    description: Path to a file or directory containing a custom CA cert chain that is imported into the Java runtime cacerts store. 

outputs:
  sarif-path:
    description: The path to the Sarif file produced from the scan.
    value: ${{ steps.sarif-path-gen.outputs.sarif-path }}


runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Resolve CxFlow
      if: inputs.cxflow-jar-path == ''
      shell: bash
      run: | 

        if [ "${{ inputs.cxflow-version }}" == "latest" ]; then
          CXFLOW_JAR=$(curl -s https://api.github.com/repos/checkmarx-ltd/cx-flow/releases/latest | \
            jq ".assets[].browser_download_url" | \
            sed -r 's/.?http.*\/(.+\.jar).?$/\1/g')

          CXFLOW_VERSION=$(echo $CXFLOW_JAR | sed -r 's/cx-flow-(.+).jar/\1/g')
        else
          CXFLOW_VERSION=${{ inputs.cxflow-version }}
          CXFLOW_JAR=$(curl -s https://api.github.com/repos/checkmarx-ltd/cx-flow/releases | \
            jq ".[].assets[].browser_download_url" | \
            grep -E "$CXFLOW_VERSION(-java11)?.jar" | \
            head -n 1 | \
            sed -r 's/.?http.*\/(.+(-java11)?.jar).?$/\1/g')

        fi

        echo "CXFLOW_VERSION=$CXFLOW_VERSION" >> "$GITHUB_ENV"
        echo "CXFLOW_JAR=$CXFLOW_JAR" >> "$GITHUB_ENV"
        echo "CXFLOW_FOLDER=$(realpath ../cxflow-$GITHUB_REPOSITORY_OWNER)" >> "$GITHUB_ENV"
        echo Using CxFlow JAR: $CXFLOW_JAR


    - name: Downloading CxFlow
      shell: bash
      if: inputs.cxflow-jar-path == ''
      run: |
        [[ ! -d "${{ env.CXFLOW_FOLDER }}" ]] && mkdir ${{ env.CXFLOW_FOLDER }} || :
        [[ ! -f  ${{ env.CXFLOW_FOLDER }}/${{ env.CXFLOW_JAR}} ]] && wget -q -O ${{ env.CXFLOW_FOLDER }}/${{ env.CXFLOW_JAR}} \
        https://github.com/checkmarx-ltd/cx-flow/releases/download/${{ env.CXFLOW_VERSION }}/${{ env.CXFLOW_JAR }} || :


    - name: Set CxFlow jar location environment variables
      shell: bash
      if: inputs.cxflow-jar-path != ''
      run: |
        echo "CXFLOW_FOLDER=$(dirname $(realpath ${{ inputs.cxflow-jar-path }}) )" >> "$GITHUB_ENV"
        echo "CXFLOW_JAR=$(basename ${{ inputs.cxflow-jar-path }})" >> "$GITHUB_ENV"


    - name: Setup App Name
      shell: bash
      run: |

        if [ "${{ inputs.app-name }}" == "" ]; then
          echo "APPNAME=$GITHUB_REPOSITORY" >> "$GITHUB_ENV"
        else
          echo "APPNAME=${{ inputs.app-name }}" >> "$GITHUB_ENV"        
        fi

    - name: Use custom config YAML 
      shell: bash
      if: inputs.application-yaml-path != ''
      run: |
        echo "CONFIG_PARAM=--spring.config.location='${{ inputs.application-yaml-path }}'" >> "$GITHUB_ENV"


    - name: Use default config YAML 
      shell: bash
      if: inputs.application-yaml-path == ''
      run: |
        echo "CONFIG_PARAM=--spring.config.location='$GITHUB_ACTION_PATH/cxflow-defaults.yml'" >> "$GITHUB_ENV"

    - name: Set params for PR
      shell: bash
      if: github.event_name == 'pull_request'
      run: |
        echo "CXFLOW_FEEDBACK_CHANNEL=${{ inputs.pull-request-feedback-channel }}" >> "$GITHUB_ENV"
        echo "CXFLOW_FEEDBACK_PARAMS=--bug-tracker='${{ inputs.pull-request-feedback-channel }}' --merge-id='${{ github.event.number }}'" >> "$GITHUB_ENV"
        echo "CXFLOW_EVENT_PARAMS=${{ inputs.pull-request-cxflow-params }}" >> "$GITHUB_ENV"
        echo "PROPER_BRANCH_NAME=${{ github.head_ref }}" >> "$GITHUB_ENV"


    - name: Set params for push
      shell: bash
      if: github.event_name != 'pull_request'
      run: |
        echo "CXFLOW_FEEDBACK_CHANNEL=${{ inputs.push-feedback-channel }}" >> "$GITHUB_ENV"
        echo "CXFLOW_FEEDBACK_PARAMS=--bug-tracker='${{ inputs.push-feedback-channel }}'" >> "$GITHUB_ENV"
        echo "CXFLOW_EVENT_PARAMS=${{ inputs.push-cxflow-params }}" >> "$GITHUB_ENV"
        echo "PROPER_BRANCH_NAME=${{ github.ref_name }}" >> "$GITHUB_ENV"

    - name: Set project name
      shell: bash
      run: |
        if [ "${{ inputs.project-name }}" == "" ]; then
          PROJECT_NAME="$GITHUB_REPOSITORY-{branch}"
        else
          PROJECT_NAME="${{ inputs.project-name }}"
        fi

        PROJECT_NAME=$(echo $PROJECT_NAME | sed -E "s/(.*)(\{branch\})(.*)/\1${{ env.PROPER_BRANCH_NAME }}\3/")
        echo "PROJECT_NAME=$PROJECT_NAME" >> "$GITHUB_ENV"

    - name: Set log level
      shell: bash
      run: echo "CXFLOW_LOGLEVEL_PARAMS=--logging.level.com.checkmarx='${{ inputs.sast-log-level }}'" >> "$GITHUB_ENV"


    - name: Set wire trace
      if: inputs.enable-wire-trace == 'true'
      shell: bash
      run: echo "WIRE_TRACE_PARAMS=--logging.level.org.apache.http.wire=TRACE" >> "$GITHUB_ENV"


    - name: Container Registry Login
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
      if: inputs.docker-login-username != '' && inputs.docker-login-password != '' 
      with:
        registry: ${{ inputs.docker-login-registry }}
        username: ${{ inputs.docker-login-username }}
        password: ${{ inputs.docker-login-password }}

    - name: Set up Docker Buildx
      if: inputs.scaresolver-tag != '' || inputs.build-container-tag != ''
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

    - name: Set Temp Paths
      shell: bash
      run: |
        RESOLVER=$(mktemp -d -p "$GITHUB_ACTION_PATH")
        echo "RESOLVER_PATH=$RESOLVER" >> "$GITHUB_ENV"

        TOOLKIT=$(mktemp -d -p "$GITHUB_ACTION_PATH")
        echo "TOOLKIT_PATH=$TOOLKIT" >> "$GITHUB_ENV"


    - name: Import custom certs
      if: inputs.custom-ca-path != ''
      shell: bash
      run: |
        if [ -f "${{ inputs.custom-ca-path }}" ];
        then
          keytool -importcert -cacerts -storepass changeit -noprompt -file "${{ inputs.custom-ca-path }}"
          cp "${{ inputs.custom-ca-path }}" "${{ env.TOOLKIT_PATH }}"/cacerts/
        fi

        if [ -d "${{ inputs.custom-ca-path }}" ];
        then
          for CA in $(ls ${{ inputs.custom-ca-path }});
          do
            keytool -alias "$CA" -importcert -cacerts -storepass changeit -noprompt -file "${{ inputs.custom-ca-path }}/${CA}" \
              && echo "Imported $CA" || echo "$CA was not imported"

            cp "$CA" "${{ env.TOOLKIT_PATH }}"/cacerts/
          done
        fi



    - name: Set SCAResolver parameters for scaresolver-tag
      shell: bash
      if: inputs.scaresolver-tag != ''
      run: |
        echo "CONTAINER_TAG=${{ inputs.scaresolver-tag }}" >> "$GITHUB_ENV"
        cp $GITHUB_ACTION_PATH/ScaResolver "${{ env.RESOLVER_PATH }}"
        echo "SCA_RESOLVER_CONFIG=--sca.enable-sca-resolver=true --sca.path-to-sca-resolver='${{ env.RESOLVER_PATH }}'" >> "$GITHUB_ENV"

    - name: Download Supply Chain Toolkit
      shell: bash
      if: inputs.scaresolver-tag == ''
      run: |
        wget -q -O ${{ env.TOOLKIT_PATH }}/build-environment.zip https://github.com/checkmarx-ts/cx-supply-chain-toolkit/releases/latest/download/build-environment.zip
        unzip ${{ env.TOOLKIT_PATH }}/build-environment.zip -d ${{ env.TOOLKIT_PATH }}

    - name: Set SCAResolver parameters for runner execution
      shell: bash
      if: inputs.scaresolver-tag == '' && inputs.build-container-tag == ''
      run: |
        RESOLVER=$( "${{ env.TOOLKIT_PATH }}"/download_resolver.sh "${{ env.RESOLVER_PATH }}")
        echo "SCA_RESOLVER_CONFIG=--sca.enable-sca-resolver=true --sca.path-to-sca-resolver='$RESOLVER'" >> "$GITHUB_ENV"

    - name: Set SCAResolver parameters for autobuild execution
      shell: bash
      if: inputs.scaresolver-tag == '' && inputs.build-container-tag != ''
      run: |
        CONTAINER_TAG=$(${{ env.TOOLKIT_PATH }}/autobuild.sh -t "${{ inputs.build-container-tag }}" -d "${{ env.TOOLKIT_PATH }}" -u -g -a "--load")
        echo "CONTAINER_TAG=$CONTAINER_TAG" >> "$GITHUB_ENV"

        cp $GITHUB_ACTION_PATH/ScaResolver "${{ env.RESOLVER_PATH }}"
        echo "SCA_RESOLVER_CONFIG=--sca.enable-sca-resolver=true --sca.path-to-sca-resolver='${{ env.RESOLVER_PATH }}'" >> "$GITHUB_ENV"


    - name: Set Sarif File Path
      id: sarif-path-gen
      shell: bash
      run: |
        echo "SARIF_FILE=${{ env.CXFLOW_FOLDER }}/${{ github.run_id }}.sarif" >> "$GITHUB_ENV"
        echo "sarif-path=${{ env.CXFLOW_FOLDER }}/${{ github.run_id }}.sarif" >> "$GITHUB_OUTPUT"


    - name: Enable Scanners
      shell: bash
      run: |
        SCANNERS=""
        [[ "${{ inputs.disable-sast-scan }}" == "false" ]] && SCANNERS="sast," || :
        [[ "${{ inputs.disable-sca-scan }}" == "false" ]] && SCANNERS="${SCANNERS}sca" || :
        echo "SCANNER_CONFIG=--cx-flow.enabled-vulnerability-scanners='${SCANNERS}'" >> "$GITHUB_ENV"


    - name: Orchestrate scans with CxFlow
      if: inputs.disable-sast-scan == 'false' || inputs.disable-sca-scan == 'false'
      shell: bash
      env:
        CHECKMARX_BASE_URL: ${{ inputs.sast-url }}
        CHECKMARX_URL: ${{ inputs.sast-url }}/cxrestapi
        CHECKMARX_USERNAME: ${{ inputs.sast-username }}
        CHECKMARX_PASSWORD: ${{ inputs.sast-password }}
        SCA_TENANT: ${{ inputs.sca-tenant }}
        SCA_USERNAME: ${{ inputs.sca-username }}
        SCA_PASSWORD: ${{ inputs.sca-password }}
        CONTAINER_TAG: ${{ env.CONTAINER_TAG }}
        SARIF_FILE_PATH: ${{ env.SARIF_FILE }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_APIURL: ${{ github.api_url }}/repos
        GITHUB_URL: ${{ github.server_url }}
      run: |
        set +e

        java ${{ inputs.java-opts }} ${{ inputs.java-props }} ${{ inputs.spring-props }} \
          -jar ${{ env.CXFLOW_FOLDER }}/${{ env.CXFLOW_JAR}} \
          ${{ env.CONFIG_PARAM }} \
          --scan --f=. \
          ${{ env.SCA_RESOLVER_CONFIG }} \
          --cx-team='${{ inputs.sast-team }}' \
          --cx-project='${{ env.PROJECT_NAME }}' \
          --namespace='${{ github.repository_owner }}' \
          --repo-name='${{ github.event.repository.name }}' \
          --branch='${{ env.PROPER_BRANCH_NAME }}' \
          --default-branch='${{ inputs.default-branch }}' \
          ${{ env.CXFLOW_FEEDBACK_PARAMS }} \
          ${{ env.CXFLOW_LOGLEVEL_PARAMS }} \
          ${{ env.WIRE_TRACE_PARAMS }} \
          ${{ env.SCANNER_CONFIG }} \
          --SHA='${{ github.sha }}' \
          --app='${{ env.APPNAME }}' \
          ${{ inputs.cxflow-params }} \
          ${{ env.CXFLOW_EVENT_PARAMS }}

        echo "CXFLOW_RESULT=$?" >> "$GITHUB_ENV"


    - name: Upload Sarif Results
      if: inputs.upload-sarif-file == 'true' && env.CXFLOW_FEEDBACK_CHANNEL == 'Sarif' && (inputs.disable-sast-scan == 'false' || inputs.disable-sca-scan == 'false')
      uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c
      with:
        sarif_file: ${{ env.SARIF_FILE }}


    - name: Remove Sarif File
      if: env.CXFLOW_FEEDBACK_CHANNEL == 'Sarif' && inputs.delete-sarif-file == 'true'
      shell: bash
      run: |
        [[ -f "${{ env.SARIF_FILE }}" ]] && rm -f ${{ env.SARIF_FILE }} || :


    - name: Finalize on Success
      if: ${{ !cancelled() }}
      shell: bash
      run: exit ${{ env.CXFLOW_RESULT }}

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        [ -d ${{ env.RESOLVER_PATH }} ] && rm -rf ${{ env.RESOLVER_PATH }} || :
        [ -d ${{ env.TOOLKIT_PATH }} ] && rm -rf ${{ env.TOOLKIT_PATH }} || :
    
    

branding:
  color: 'green'
  icon: 'layers'
